apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-apps
  labels:
    app: my-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - name: my-web
        image: docker.io/kdua1/apps:latest
        ports:
        - containerPort: 8080
          name: my-web
      restartPolicy: Always   


---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-web
  type: ClusterIP  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
